services:
  app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    ports:
      - "${APP_PORT:-8000}:8000"
    # depends_on:
    #   - postgres
    # networks:
    #   - postgres