"""Add wallet_address to users table

Revision ID: add_wallet_address
Revises: d32a6fcf8ac8
Create Date: 2025-08-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_wallet_address'
down_revision = 'd32a6fcf8ac8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wallet_address', sa.String(255), nullable=True))
    op.create_index('ix_users_wallet_address', 'users', ['wallet_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_wallet_address', table_name='users')
    op.drop_column('users', 'wallet_address')
    # ### end Alembic commands ###
